//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Coki.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.factura_cabecera = new HashSet<factura_cabecera>();
        }
    
        public int idusuario { get; set; }
        public string apeynom { get; set; }
        public string tel { get; set; }
        public string nomusuario { get; set; }
        public string contraseña { get; set; }
        public Nullable<int> idtipousuario { get; set; }
        public Nullable<int> estado { get; set; }
        public string correo { get; set; }
        public string dni { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_cabecera> factura_cabecera { get; set; }
        public virtual tipo_usuario tipo_usuario { get; set; }
    }
}
